
version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    image: auth-service
    container_name: auth-service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/streamingapp
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  streaming-service:
    image: streaming-service
    container_name: streaming-service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/streamingapp
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  admin-service:
    image: admin-service
    container_name: admin-service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/streamingapp
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  chat-service:
    image: chat-service
    container_name: chat-service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/streamingapp
    ports:
      - "3004:3004"
    depends_on:
      - mongo

  frontend:
    image: frontend-service
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - streaming-service
      - admin-service
      - chat-service

volumes:
  mongo_data: