apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: chat-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3004
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/streamingapp
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - port: 3004
    targetPort: 3004