apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
      - name: streaming-service
        image: streaming-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/streamingapp
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  selector:
    app: streaming-service
  ports:
  - port: 3002
    targetPort: 3002